spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://10.75.49.155:2228;databaseName=ISG1_SMS;encrypt=true;trustServerCertificate=true;
spring.datasource.username=isgadmin
spring.datasource.password=Password@123
debug=true
crypto.public-key-path=D:\key\ICICI_UAT_PublicCert.pem
#server.port = 9080
#debug=true
##topic-partitions= 4
#kafka-topic = DEBITCARD
#sslFlag : N
#spring.kafka.bootstrap-servers : localhost:9092
#spring.kafka.consumer.group-id:myGroup
#spring.kafka.consumer.auto-offset-reset:earliest
#spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
 
#ssl.keystore.path=/home/op_317/SSL_Kafka_Provided_Cert/erecon.keystore.jks
#ssl.keystore.password=icicibank
#ssl.truststore.path=/home/op_317/SSL_Kafka_Provided_Cert/erecon.truststore.jks
#ssl.truststore.password=icicibank
#kafka.bootstrap.server=localhost:9092
 
#spring.kafka.producer.bootstrap-servers: localhost:9092
#spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
 
############connectionString=rtGBmI26Iot0vbKb4Dtj27ZC599Id6cfUosqJNdEZppvwkXBIkFB5pn+VEDB8x2anSc8WW2bwId3TCDmUn6hk4FhhqfrvBY2VH0OcngsEtX6JcOfcWtD8oLQc91jeGix
############PREFIXMSGID=1
############address=10.50.52.221
############port=80
############username=36470
############Password=infotech(9
############Domain=ICICIBANKLTD
 
###########frompipe  = 111
###########topipe = 112
###########npfrompipe  = 111
###########nptopipe = 112
###########clientip = 10.26.60.107,10.26.60.135,10.26.60.108,0:0:0:0:0:0:0:1,127.0.0.1
###########SMTP_PORT=25
##################KAT=OTAwMDA\=
##################CLIENTIPPATH=D\:/vi/ws/testjava/testjava/clientIPs
##################MAXCONN=1
#UID=aXNnYWRtaW4\=
##################UID=aXNnYWRtaW4=
##################TIME=MzAw
#139 server
##################PSWD=aXNnYWRtaW4xMjM0
#190 server
#PSWD=UGFzc3dvcmRAMTIz
#Old Size
################MAX=MTUw
#New Size
#MAX=MTAwMA==
################CLS=Y29tLm1pY3Jvc29mdC5zcWxzZXJ2ZXIuamRiYy5TUUxTZXJ2ZXJEcml2ZXI\=
################CIT=MzA\=
#URL=amRiYzpzcWxzZXJ2ZXI6Ly8xMC43NS44LjE5MDoyMjI4O2RhdGFiYXNlPUlTRzE=
#Databse Name ISG
#URL=amRiYzpzcWxzZXJ2ZXI6Ly8xMC4xNi4yNDAuMTM5OjczMjU7ZGF0YWJhc2U9SVNH
#Databse Name ISG1
################URL=amRiYzpzcWxzZXJ2ZXI6Ly8xMC4xNi4yNDAuMTM5OjczMjU7ZGF0YWJhc2U9SVNHMQ==
#Database Name ISG1_SMS
#URL=amRiYzpzcWxzZXJ2ZXI6Ly8xMC43NS44LjE5MDoyMjI4O2RhdGFiYXNlPUlTRzFfU01T
#URL=amRiYzpzcWxzZXJ2ZXI6Ly8xMC4xNi4yNDAuMTM5OjczMjU=
#URL=amRiYzpzcWxzZXJ2ZXI6Ly8xMC4yNC4xNTUuNjg6NzMyNTtkYXRhYmFzZU5hbWU9SVNHMQ==
#ipauth=Y
#SMTP_HOST=10.16.0.39
#NOT=MTUw
#MAXCL=MzAw
#MIN=NQ\=\=
#server.tomcat.accept-count=100
#server.connection-timeout=10
#server.tomcat.max-connections=10000
#server.tomcat.max-http-post-size=3MB
#server.tomcat.max-threads=100
#server.tomcat.max-swallow-size=2MB
#server.tomcat.min-spare-threads=10
#server.max-http-header-size=8MB
logging.config=classpath:log4j2.properties
config.path=classpath:config.properties
 
 
 